// Modal
export const SET_LOGIN_MODAL = "SET_LOGIN_MODAL";
export const SET_POSITION_MODAL = "SET_POSITION_MODAL";


// User
export const SET_USER_LOGIN = "SET_USER_LOGIN";
export const LOG_OUT_USER = "LOG_OUT_USER";

// Application
export const ADD_POSITION = "ADD_POSITION";
export const REMOVE_POSITION = "REMOVE_POSITION";
export const PRIORITIZE_POSITION = "PRIORITIZE_POSITION";
export const DEPRIORITIZE_POSITION = "DEPRIORITIZE_POSITION";